vulnerabilities:
  - id: CVE-2026-25128
    paths:
      - "package-lock.json"
    statement: downstream dependency of fast-xml-parser
    expired_at: 2026-06-01
  - id: CVE-2026-25547
    paths:
      - "package-lock.json"
    statement: downstream dependency of @isaacs/brace-expansion
    expired_at: 2026-06-01
  - id: CVE-2026-26278
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb
    expired_at: 2026-06-01
  - id: CVE-2026-26996
    statement: minimatch vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-27903
    statement: minimatch vulnerability accepted as risk
    expired_at: 2026-06-01
  - id: CVE-2026-27904
    statement: minimatch vulnerability accepted as risk
    expired_at: 2026-06-01
