AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prescriptions api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    Runtime: nodejs18.x
    Environment:
      Variables:
        TargetSpineServer: !Ref TargetSpineServer
        NODE_OPTIONS: --enable-source-maps
        SpinePrivateKeyARN: !ImportValue ci-resources:SpinePrivateKey
        SpinePublicCertificateARN: !ImportValue ci-resources:SpinePublicCertificate
        SpineASIDARN: !ImportValue ci-resources:SpineASID
        SpinePartyKeyARN: !ImportValue ci-resources:SpinePartyKey
        SpineCAChainARN: !ImportValue ci-resources:SpineCAChain

Parameters:
  TargetSpineServer:
    Type: String
    Description: TargetSpineServer
    Default: none
  SplunkHECToken:
    Type: String
    Description: HEC Token for Cloudformation to Splunk Firehose
    Default: none
  SplunkHECEndpoint:
    Type: String
    Description: HEC Endpoint for Cloudformation to Splunk Firehose
    Default: none
  TruststoreVersion:
    Type: String
    Description: TruststoreVersion
    Default: none
  EnableMutualTLS:
    Type: String
    Description: Whether to use mutual TLS
    Default: false
    AllowedValues: [true, false]
  EnableSplunk:
    Type: String
    Description: Whether to use splunk
    Default: false
    AllowedValues: [true, false]
  VersionNumber:
    Type: String
    Description: Current release version
    Default: "xxx"
  CommitId:
    Type: String
    Description: Most recent commit hash
    Default: "xxx"

Conditions:
  ShouldUseMutualTLS: !Equals [true, !Ref EnableMutualTLS]
  ShouldUseSplunk: !Equals [true, !Ref EnableSplunk]

Resources:
  SplunkFirehose:
    Type: AWS::Serverless::Application
    Properties:
      Location: template_splunk_firehose.yaml
      Parameters:
        SplunkHECToken: !Ref SplunkHECToken
        SplunkHECEndpoint: !Ref SplunkHECEndpoint
        EnableSplunk: !Ref EnableSplunk

  GetSecretsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: get-secrets-layer
      Description: get secrets layer
      ContentUri: packages/getSecretLayer/lib/get-secrets-layer.zip
      RetentionPolicy: Retain

  # getMyPrescription lambda
  GetMyPrescriptionsRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
  GetMyPrescriptionsLambdaPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-lambda-logging"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${GetMyPrescriptionsLogGroup}"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${GetMyPrescriptionsLogGroup}:log-stream:*"
      Roles:
        - !Ref GetMyPrescriptionsRole
  GetMyPrescriptionsKMSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-CloudWatchKMS-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:ReEncrypt*
            Resource:
              - !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
      Roles:
        - !Ref GetMyPrescriptionsRole
  GetMyPrescriptionsSecretsKMSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-SecretsKMS-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              - !ImportValue ci-resources:SecretsKMSKey
      Roles:
        - !Ref GetMyPrescriptionsRole
  GetMyPrescriptionsSecretsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-secrets-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !ImportValue ci-resources:SpinePrivateKey
              - !ImportValue ci-resources:SpinePublicCertificate
              - !ImportValue ci-resources:SpineASID
              - !ImportValue ci-resources:SpinePartyKey
              - !ImportValue ci-resources:SpineCAChain
      Roles:
        - !Ref GetMyPrescriptionsRole
  GetMyPrescriptionsLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetMyPrescriptions}"
      RetentionInDays: 90
      KmsKeyId: !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
  GetMyPrescriptionsSplunkSubscriptionFilter:
    Condition: ShouldUseSplunk
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SplunkFirehose.Outputs.SplunkSubscriptionFilterRole
      LogGroupName: !Ref GetMyPrescriptionsLogGroup
      FilterPattern: "" # All logs
      DestinationArn: !GetAtt SplunkFirehose.Outputs.SplunkDeliveryStream
  GetMyPrescriptions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages
      Handler: app.handler
      Role: !GetAtt GetMyPrescriptionsRole.Arn
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/get-secrets-layer
      Layers:
        - !Ref GetSecretsLayer
      Events:
        getMyPrescriptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /Bundle
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        tsconfig: getMyPrescriptions/tsconfig.json
        EntryPoints:
          - getMyPrescriptions/src/app.ts

  # capabilityStatement lambda
  CapabilityStatementRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
  CapabilityStatementLambdaPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-lambda-logging"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${CapabilityStatementLogGroup}"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${CapabilityStatementLogGroup}:log-stream:*"
      Roles:
        - !Ref CapabilityStatementRole
  CapabilityStatementKMSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-CloudWatchKMS-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:ReEncrypt*
            Resource:
              - !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
      Roles:
        - !Ref CapabilityStatementRole
  CapabilityStatementLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CapabilityStatement}"
      RetentionInDays: 90
      KmsKeyId: !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
  CapabilityStatementSplunkSubscriptionFilter:
    Condition: ShouldUseSplunk
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SplunkFirehose.Outputs.SplunkSubscriptionFilterRole
      LogGroupName: !Ref CapabilityStatementLogGroup
      FilterPattern: "" # All logs
      DestinationArn: !GetAtt SplunkFirehose.Outputs.SplunkDeliveryStream
  CapabilityStatement:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages
      Handler: app.handler
      Role: !GetAtt CapabilityStatementRole.Arn
      Events:
        capabilityStatement:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /metadata
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        tsconfig: capabilityStatement/tsconfig.json
        EntryPoints:
          - capabilityStatement/src/app.ts

  # _status endpoint lambda
  StatusLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
  StatusLambdaLambdaPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-lambda-logging"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${StatusLambdaLogGroup}"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${StatusLambdaLogGroup}:log-stream:*"
      Roles:
        - !Ref StatusLambdaRole
  StatusLambdaKMSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-CloudWatchKMS-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:ReEncrypt*
            Resource:
              - !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
      Roles:
        - !Ref StatusLambdaRole
  StatusLambdaSecretsKMSPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-SecretsKMS-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              - !ImportValue ci-resources:SecretsKMSKey
      Roles:
        - !Ref StatusLambdaRole
  StatusLambdaSecretsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-secrets-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !ImportValue ci-resources:SpinePrivateKey
              - !ImportValue ci-resources:SpinePublicCertificate
              - !ImportValue ci-resources:SpineASID
              - !ImportValue ci-resources:SpinePartyKey
              - !ImportValue ci-resources:SpineCAChain
      Roles:
        - !Ref StatusLambdaRole
  StatusLambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StatusLambda}"
      RetentionInDays: 30
      KmsKeyId: !GetAtt SplunkFirehose.Outputs.CloudWatchKMSKey
  StatusLambdaSplunkSubscriptionFilter:
    Condition: ShouldUseSplunk
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !GetAtt SplunkFirehose.Outputs.SplunkSubscriptionFilterRole
      LogGroupName: !Ref StatusLambdaLogGroup
      FilterPattern: "" # All logs
      DestinationArn: !GetAtt SplunkFirehose.Outputs.SplunkDeliveryStream
  StatusLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages
      Handler: app.handler
      Role: !GetAtt StatusLambdaRole.Arn
      Environment:
        Variables:
          VERSION_NUMBER: !Ref VersionNumber
          COMMIT_ID: !Ref CommitId
          AWS_LAMBDA_EXEC_WRAPPER: /opt/get-secrets-layer
      Layers:
        - !Ref GetSecretsLayer
      Events:
        status:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /_status
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        tsconfig: statusLambda/tsconfig.json
        EntryPoints:
          - statusLambda/src/app.ts

  # TLS cert for custom domain
  GenerateCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Fn::Join:
          - "."
          - - !Ref "AWS::StackName"
            - Fn::ImportValue: route53-resources:domain
      DomainValidationOptions:
        - DomainName:
            Fn::Join:
              - "."
              - - !Ref "AWS::StackName"
                - Fn::ImportValue: route53-resources:domain
          HostedZoneId:
            Fn::ImportValue: route53-resources:ZoneID

  # Http api
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Domain:
        DomainName:
          Fn::Join:
            - "."
            - - !Ref "AWS::StackName"
              - Fn::ImportValue: route53-resources:domain
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId:
            Fn::ImportValue: route53-resources:ZoneID
        EndpointConfiguration: REGIONAL
        SecurityPolicy: TLS_1_2
        MutualTlsAuthentication:
          TruststoreUri:
            "Fn::If":
              - ShouldUseMutualTLS
              - Fn::Join:
                  - "/"
                  - - "s3:/"
                    - !Select [
                        5,
                        !Split [
                          ":",
                          Fn::ImportValue: ci-resources:TrustStoreBucket,
                        ],
                      ]
                    - "truststore.pem"
              - !Ref "AWS::NoValue"
          TruststoreVersion:
            "Fn::If":
              - ShouldUseMutualTLS
              - !Ref TruststoreVersion
              - !Ref "AWS::NoValue"
      DisableExecuteApiEndpoint:
        "Fn::If":
          - ShouldUseMutualTLS
          - true
          - !Ref "AWS::NoValue"
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGwAccessLogs.Arn
        Format: "{ \
          'requestTime': '$context.requestTime', \
          'apiId': '$context.apiId', \
          'accountId': '$context.accountId', \
          'resourcePath': '$context.resourcePath', \
          'stage': '$context.stage', \
          'requestId': '$context.requestId', \
          'extendedRequestId': '$context.extendedRequestId', \
          'httpMethod': '$context.httpMethod', \
          'protocol': '$context.protocol', \
          'path': '$context.path', \
          'domainName': '$context.domainName', \
          'identity': { \
          'sourceIp': '$context.identity.sourceIp', \
          'userAgent': '$context.identity.userAgent', \
          'clientCert':{ \
          'subjectDN': '$context.identity.clientCert.subjectDN', \
          'issuerDN': '$context.identity.clientCert.issuerDN', \
          'serialNumber': '$context.identity.clientCert.serialNumber', \
          'validityNotBefore': '$context.identity.clientCert.validity.notBefore', \
          'validityNotAfter': '$context.identity.clientCert.validity.notAfter', \
          }}}"

  ApiGwAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${HttpApiGateway}"
      RetentionInDays: 30

  ApiGwLoggingPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-api-gw-logging"
      PolicyDocument:
        Version: "2012-10-07"
        Statement:
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:GetLogEvents
              - logs:FilterLogEvents
            Resource:
              - !GetAtt ApiGwAccessLogs.Arn
          - Effect: Allow
            Action:
              - logs:CreateLogDelivery
              - logs:PutResourcePolicy
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:CreateLogGroup
              - logs:DescribeResourcePolicies
              - logs:GetLogDelivery
              - logs:ListLogDeliveries
            Resource:
              - "*"
