name: 'Create confluence release notes'
description: 'Do release note actions in confluence and jira'
inputs:
  TARGET_ENVIRONMENT:
    required: true
    description: "Target Environment"
  RELEASE_TAG:
    required: false
    description: "The tag we are releasing - only used for create_rc_release_notes"
  CONFLUENCE_PAGE_ID:
    required: true
    description: "The id of confluence page to update or create under"
  CREATE_RC_RELEASE_NOTES:
    required: true
    description: "whether to create rc release notes page instead of normal release notes"
    default: "false"
  DEV_CLOUD_FORMATION_DEPLOY_ROLE:
    required: true
    description: "The dev cloud formation deploy role"
  TARGET_CLOUD_FORMATION_DEPLOY_ROLE:
    required: true
    description: "The target cloud formation deploy role"
  DRY_RUN:
    required: false
    description: "whether to use a dry run and do not connect to anything"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: connect to target account
      if: inputs.DRY_RUN != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.TARGET_CLOUD_FORMATION_DEPLOY_ROLE }}
        role-session-name: github-actions
    - name: Get deployed tag on target
      shell: bash
      run: |
        # get current deployed tag on target
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          export current_deployed_tag=$(aws cloudformation describe-stacks --stack-name ${{ inputs.TARGET_ENVIRONMENT }}-ci --query "Stacks[0].Tags[?Key=='version'].Value" --output text)
        else
          export current_deployed_tag="current_deployed_tag"
        fi
        echo "current_deployed_tag=${current_deployed_tag}" >> "$GITHUB_ENV"
    - name: connect to dev account
      if: inputs.DRY_RUN != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
        role-session-name: github-actions
    - name: get current dev tag
      shell: bash
      run: |
        # get current dev tag
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          export dev_tag=$(aws cloudformation describe-stacks --stack-name dev-ci --query "Stacks[0].Tags[?Key=='version'].Value" --output text)
        else
          export dev_tag="dev_tag"
        fi
        echo "dev_tag=${dev_tag}" >> "$GITHUB_ENV"
    - name: create int release notes
      shell: bash
      if: inputs.TARGET_ENVIRONMENT == 'int' && inputs.CREATE_RC_RELEASE_NOTES == 'false'
      run: |
        # create int release notes
        cat <<EOF > payload.json
        { 
            "currentTag": "$current_deployed_tag", 
            "targetTag": "$dev_tag", 
            "repoName": "prescriptionsforpatients", 
            "targetEnvironment": "INT", 
            "productName": "Prescritpions for Patients AWS layer", 
            "releaseNotesPageId": "693750027", 
            "releaseNotesPageTitle": "Current PfP AWS layer release notes - INT"
        }
        EOF
        cat payload.json
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          aws lambda invoke --function-name release-notes-createReleaseNotes \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json out.txt
        fi
    - name: create int rc release notes
      shell: bash
      if: inputs.TARGET_ENVIRONMENT == 'int' && inputs.CREATE_RC_RELEASE_NOTES == 'true'
      run: |
        # create int rc release notes
        release_tag="${{ inputs.RELEASE_TAG }}"
        cat <<EOF > payload.json
        { 
            "currentTag": "$current_deployed_tag", 
            "targetTag": "$release_tag", 
            "repoName": "prescriptionsforpatients", 
            "targetEnvironment": "INT", 
            "productName": "Prescritpions for Patients AWS layer", 
            "releaseNotesPageId": "710051481", 
            "releaseNotesPageTitle": "PfP-AWS-$release_tag - Deployed to [INT] on $(date +'%d-%m-%y')",
            "createReleaseCandidate": "true",
            "releasePrefix": "PfP-AWS-"
        }
        EOF
        cat payload.json
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          aws lambda invoke --function-name release-notes-createReleaseNotes \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json out.txt
        fi
    - name: create prod release notes
      shell: bash
      if: inputs.TARGET_ENVIRONMENT == 'prod'
      run: |
        # create prod release notes
        cat <<EOF > payload.json
        { 
            "currentTag": "$current_deployed_tag", 
            "targetTag": "$dev_tag", 
            "repoName": "prescriptionsforpatients", 
            "targetEnvironment": "PROD", 
            "productName": "Prescritpions for Patients AWS layer", 
            "releaseNotesPageId": "693750029", 
            "releaseNotesPageTitle": "Current PfP AWS layer release notes - PROD"
        }
        EOF
        cat payload.json
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          aws lambda invoke --function-name release-notes-createReleaseNotes \
            --cli-binary-format raw-in-base64-out \
            --payload file://payload.json out.txt
        fi
