AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PfP Cloudwatch alarms and related resources

Parameters:
  StackName:
    Type: String

  GetMyPrescriptionsFunctionName:
    Type: String

  EnrichPrescriptionsFunctionName:
    Type: String

  EnableAlerts:
    Type: String

Resources:
  ServiceSearchErrorsLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: ServiceSearchErrors
      # Match logs with $.message starting with "error in request to serviceSearch"
      FilterPattern: !Sub '{ ($.level = "ERROR") && ($.function_name = "${GetMyPrescriptionsFunctionName}") && $.message = %error in request to serviceSearch% }' # function_name included to allow it to be set as a dimension on the metric
      LogGroupName:
        Fn::ImportValue: !Sub ${StackName}:functions:${GetMyPrescriptionsFunctionName}:LambdaLogGroupName
      MetricTransformations:
        - MetricNamespace: LambdaLogFilterMetrics
          MetricName: ServiceSearchErrorCount
          MetricValue: 1
          Unit: Count
          Dimensions: # dimensions for a logs filter metric can only be a field/value from the filter pattern
            - Key: FunctionName
              Value: $.function_name

  ServiceSearchErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Count of Service Search errors
      AlarmName: !Sub ${StackName}_ServiceSearch_Errors
      Namespace: LambdaLogFilterMetrics
      MetricName: ServiceSearchErrorCount
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetMyPrescriptionsFunctionName
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching
      ActionsEnabled: !Ref EnableAlerts
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn

  ServiceSearchUnhandledErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Count of Service Search unhandled errors
      AlarmName: !Sub ${StackName}_ServiceSearch_UnhandledErrors
      Namespace: Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetMyPrescriptionsFunctionName
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching
      ActionsEnabled: !Ref EnableAlerts
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn

  GetMyPrescriptionsErrorsLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: GetMyPrescriptionsErrors
      FilterPattern: !Sub '{ ($.level = "ERROR") && ($.function_name = "${GetMyPrescriptionsFunctionName}") && ($.message != %error in request to serviceSearch%) }'
      LogGroupName:
        Fn::ImportValue: !Sub ${StackName}:functions:${GetMyPrescriptionsFunctionName}:LambdaLogGroupName
      MetricTransformations:
        - MetricNamespace: LambdaLogFilterMetrics
          MetricName: ErrorCount
          MetricValue: 1
          Unit: Count
          Dimensions:
            - Key: FunctionName
              Value: $.function_name

  GetMyPrescriptionsErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Count of GetMyPrescriptions errors
      AlarmName: !Sub ${StackName}_GetMyPrescriptions_Errors
      Namespace: LambdaLogFilterMetrics
      MetricName: ErrorCount
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetMyPrescriptionsFunctionName
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching
      ActionsEnabled: !Ref EnableAlerts
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn

  EnrichPrescriptionsErrorsLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: EnrichPrescriptionsErrors
      FilterPattern: ERROR
      LogGroupName:
        Fn::ImportValue: !Sub ${StackName}:functions:${EnrichPrescriptionsFunctionName}:LambdaLogGroupName
      MetricTransformations:
        - MetricNamespace: LambdaLogFilterMetrics
          MetricName: !Sub ${StackName}EnrichPrescriptionsErrorCount
          MetricValue: 1
          Unit: Count

  EnrichPrescriptionsErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Count of EnrichPrescriptions errors
      AlarmName: !Sub ${StackName}_EnrichPrescriptions_Errors
      Namespace: LambdaLogFilterMetrics
      MetricName: !Sub ${StackName}EnrichPrescriptionsErrorCount
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching
      ActionsEnabled: !Ref EnableAlerts
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
