AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  StackName:
    Type: String
    Default: none

Resources:
  PfPSecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: PfPSecretsKeyPolicy
        Statement:
          - Sid: EnableIAMUserPermissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: Enable read only decrypt
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:DescribeKey
              - kms:Decrypt
            Resource: "*"
            Condition:
              ArnLike:
                aws:PrincipalArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/${AWS::Region}/AWSReservedSSO_ReadOnly*"

  PfPSecretsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${StackName}-PfPSecretsKMSKey
      TargetKeyId: !Ref PfPSecretsKMSKey

  UsePfPSecretsKMSKeyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${StackName}-UsePfPSecretsKMSKey
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowKmsForSecretsEncryption
            Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:Decrypt
            Resource: !GetAtt PfPSecretsKMSKey.Arn

  PfPServiceSearchApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-PfP-ServiceSearch-API-Key
      Description: API Key for Service Search
      KmsKeyId: !Ref PfPSecretsKMSKey

  GetPfPSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading PfP secret parameters"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref PfPServiceSearchApiKeySecret

Outputs:
  PfPServiceSearchApiKeySecret:
    Description: The name of the PfP Service Search API Key secret
    Value: !Ref PfPServiceSearchApiKeySecret
    Export:
      Name: !Sub ${StackName}-PfP-ServiceSearch-API-Key

  GetPfPSecretPolicy:
    Description: ARN of policy granting permission to read secrets
    Value: !Ref GetPfPSecretPolicy
    Export:
      Name: !Sub ${StackName}-GetPfPSecretPolicy

  UsePfPSecretsKMSKeyPolicyArn:
    Description: ARN of managed policy granting PfP secrets KMS usage
    Value: !Ref UsePfPSecretsKMSKeyPolicy
    Export:
      Name: !Sub ${StackName}-UsePfPSecretsKMSKeyPolicyArn
