AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubjectClaimFilters:
    Type: CommaDelimitedList
    Default: "repo:NHSDigital/prescriptionsforpatients:*"
    Description: >
      Subject claim filter for valid tokens.
      Default allows only pull requests of the NHSDigital/prescriptionsforpatients to assume the role.
      See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims
      for examples of filtering by branch or deployment environment.

Resources:
  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      ClientIdList:
        - sts.amazonaws.com

  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              ForAnyValue:StringLike:
                token.actions.githubusercontent.com:sub: !Ref SubjectClaimFilters
      Policies:
        - PolicyName: CreateCloudFormationStack
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ListExports"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:ListStacks"
                Resource: "*"
        - PolicyName: AssumeExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: !GetAtt CloudFormationExecutionRole.Arn

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      # see https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html for permissions
      Policies:
        - PolicyName: GrantCloudFormationDeployAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateChangeSet"
                  - "iam:Attach*"
                  - "iam:Create*"
                  - "iam:Delete*"
                  - "iam:Detach*"
                  - "iam:Get*"
                  - "iam:List*"
                  - "iam:Put*"
                  - "iam:Remove*"
                  - "iam:Tag*"
                  - "iam:Untag*"
                  - "iam:Update*"
                  - "iam:PassRole"
                  - "logs:AssociateKmsKey"
                  - "logs:DisassociateKmsKey"
                  - "logs:CreateLogGroup"
                  - "logs:DeleteLogGroup"
                  - "logs:TagLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DeleteLogStream"
                  - "logs:PutRetentionPolicy"
                  - "logs:DeleteRetentionPolicy"
                  - "logs:PutSubscriptionFilter"
                  - "logs:DescribeSubscriptionFilters"
                  - "logs:DeleteSubscriptionFilter"
                  - "logs:DescribeLogGroups"
                  - "logs:CreateLogDelivery"
                  - "logs:DeleteLogDelivery"
                  - "logs:ListLogDeliveries"
                  - "logs:GetLogDelivery"
                  - "logs:UpdateLogDelivery"
                  - "logs:ListTagsLogGroup"
                  - "logs:UntagLogGroup"
                  - "lambda:Add*"
                  - "lambda:CreateFunction"
                  - "lambda:Delete*"
                  - "lambda:Get*"
                  - "lambda:List*"
                  - "lambda:Publish*"
                  - "lambda:Put*"
                  - "lambda:Remove*"
                  - "lambda:Tag*"
                  - "lambda:Untag*"
                  - "lambda:Update*"
                  - "kms:Create*"
                  - "kms:Delete*"
                  - "kms:Describe*"
                  - "kms:Get*"
                  - "kms:List*"
                  - "kms:Put*"
                  - "kms:ScheduleKeyDeletion*"
                  - "kms:Tag*"
                  - "kms:Untag*"
                  - "kms:Update*"
                  - "apigateway:DELETE"
                  - "apigateway:GET"
                  - "apigateway:POST"
                  - "apigateway:PATCH"
                  - "apigateway:PUT"
                  - "apigateway:AddCertificateToDomain"
                  - "apigateway:RemoveCertificateFromDomain"
                  - "apigateway:TagResource"
                  # s3 permissions can be removed once https://github.com/NHSDigital/prescriptionsforpatients/pull/165 is merged
                  - "s3:CreateBucket"
                  - "s3:DeleteBucket"
                  - "s3:SetBucketEncryption"
                  - "s3:PutEncryptionConfiguration"
                  - "s3:PutBucketVersioning"
                  - "s3:GetBucketTagging"
                  - "s3:PutBucketTagging"
                  - "firehose:CreateDeliveryStream"
                  - "firehose:DescribeDeliveryStream"
                  - "firehose:DeleteDeliveryStream"
                  - "firehose:UpdateDestination"
                  - "firehose:ListTagsForDeliveryStream"
                  - "firehose:TagDeliveryStream"
                  - "firehose:UntagDeliveryStream"
                  - "acm:AddTagsToCertificate"
                  - "acm:DeleteCertificate"
                  - "acm:DescribeCertificate"
                  - "acm:GetCertificate"
                  - "acm:ListCertificates"
                  - "acm:ListTagsForCertificate"
                  - "acm:RemoveTagsFromCertificate"
                  - "acm:RenewCertificate"
                  - "acm:RequestCertificate"
                  - "route53:ChangeResourceRecordSets"
                  - "route53:GetHostedZone"
                  - "route53:ListResourceRecordSets"
                  - "route53:GetChange"
                Resource: "*"

Outputs:
  CloudFormationDeployRole:
    Description: ARN of the IAM Role(CloudFormationDeployRole)
    Value: !GetAtt CloudFormationDeployRole.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "CloudFormationDeployRole"]]
  CloudFormationExecutionRole:
    Description: ARN of the IAM Role(CloudFormationExecutionRole)
    Value: !GetAtt CloudFormationExecutionRole.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "CloudFormationExecutionRole"]]
  CloudFormationExecutionRoleName:
    Description: Name of the IAM Role(CloudFormationExecutionRole)
    Value: !Ref CloudFormationExecutionRole
    Export:
      Name:
        !Join [":", [!Ref "AWS::StackName", "CloudFormationExecutionRoleName"]]
