AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubjectClaimFilters:
    Type: CommaDelimitedList
    Default: "repo:NHSDigital/prescriptionsforpatients:*"
    Description: >
      Subject claim filter for valid tokens.
      Default allows only pull requests of the NHSDigital/prescriptionsforpatients to assume the role.
      See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims
      for examples of filtering by branch or deployment environment.

Resources:
  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      ClientIdList:
        - sts.amazonaws.com

  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Ref SubjectClaimFilters
      Policies:
        - PolicyName: CreateCloudFormationStack
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:ListExports"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:ListStacks"
                Resource: "*"
        - PolicyName: AssumeExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: !GetAtt CloudFormationExecutionRole.Arn
        - PolicyName: UseArtifactBucketKMSKey
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey*"
                  - "kms:Encrypt"
                  - "kms:ReEncrypt*"
                  - "kms:Decrypt"
                Resource: !GetAtt ArtifactsBucketKMSKey.Arn

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: ManagedStackSource
          Value: AwsSamCli
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      # see https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html for permissions
      Policies:
        - PolicyName: GrantCloudFormationDeployAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateChangeSet"
                  - "iam:Attach*"
                  - "iam:Create*"
                  - "iam:Delete*"
                  - "iam:Detach*"
                  - "iam:Get*"
                  - "iam:List*"
                  - "iam:Put*"
                  - "iam:Remove*"
                  - "iam:Tag*"
                  - "iam:Untag*"
                  - "iam:Update*"
                  - "iam:PassRole"
                  - "logs:AssociateKmsKey"
                  - "logs:DisassociateKmsKey"
                  - "logs:CreateLogGroup"
                  - "logs:DeleteLogGroup"
                  - "logs:TagLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DeleteLogStream"
                  - "logs:PutRetentionPolicy"
                  - "logs:DeleteRetentionPolicy"
                  - "logs:PutSubscriptionFilter"
                  - "logs:DescribeSubscriptionFilters"
                  - "logs:DeleteSubscriptionFilter"
                  - "lambda:Add*"
                  - "lambda:CreateFunction"
                  - "lambda:Delete*"
                  - "lambda:Get*"
                  - "lambda:List*"
                  - "lambda:Publish*"
                  - "lambda:Put*"
                  - "lambda:Remove*"
                  - "lambda:Tag*"
                  - "lambda:Untag*"
                  - "lambda:Update*"
                  - "kms:Create*"
                  - "kms:Delete*"
                  - "kms:Describe*"
                  - "kms:Get*"
                  - "kms:List*"
                  - "kms:Put*"
                  - "kms:ScheduleKeyDeletion*"
                  - "kms:Tag*"
                  - "kms:Untag*"
                  - "kms:Update*"
                  - "apigateway:DELETE"
                  - "apigateway:GET"
                  - "apigateway:POST"
                  - "apigateway:PATCH"
                  - "apigateway:PUT"
                  - "apigateway:AddCertificateToDomain"
                  - "apigateway:RemoveCertificateFromDomain"
                  - "apigateway:TagResource"
                  - "s3:CreateBucket"
                  - "s3:DeleteBucket"
                  - "s3:SetBucketEncryption"
                  - "s3:PutEncryptionConfiguration"
                  - "s3:PutBucketVersioning"
                  - "firehose:CreateDeliveryStream"
                  - "firehose:DescribeDeliveryStream"
                  - "firehose:DeleteDeliveryStream"
                  - "firehose:UpdateDestination"
                  - "acm:AddTagsToCertificate"
                  - "acm:DeleteCertificate"
                  - "acm:DescribeCertificate"
                  - "acm:GetCertificate"
                  - "acm:ListCertificates"
                  - "acm:ListTagsForCertificate"
                  - "acm:RemoveTagsFromCertificate"
                  - "acm:RenewCertificate"
                  - "acm:RequestCertificate"
                  - "route53:ChangeResourceRecordSets"
                  - "route53:GetHostedZone"
                  - "route53:ListResourceRecordSets"
                  - "route53:GetChange"
                Resource: "*"
        - PolicyName: UseTrustStoreBucketKMSKey
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey*"
                  - "kms:Encrypt"
                  - "kms:ReEncrypt*"
                  - "kms:Decrypt"
                Resource: !GetAtt TrustStoreBucketKMSKey.Arn

  # KMS S3 encryption key
  ArtifactsBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-s3
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
  ArtifactsBucketKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/ArtifactsBucketKMSKeyAlias
      TargetKeyId: !Ref ArtifactsBucketKMSKey

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    # TODO uncomment this once happy with everything
    # DeletionPolicy: "Retain"
    Properties:
      Tags:
        - Key: ManagedStackSource
          Value: AwsSamCli
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${ArtifactsBucketKMSKeyAlias}"
              SSEAlgorithm: "aws:kms"

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Statement:
          - Effect: "Deny"
            Action: "s3:*"
            Principal: "*"
            Resource:
              - !Join ["", [!GetAtt ArtifactsBucket.Arn, "/*"]]
              - !GetAtt ArtifactsBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
          - Effect: "Allow"
            Action:
              - "s3:GetObject*"
              - "s3:PutObject*"
              - "s3:GetBucket*"
              - "s3:List*"
            Resource:
              - !Join ["", [!GetAtt ArtifactsBucket.Arn, "/*"]]
              - !GetAtt ArtifactsBucket.Arn
            Principal:
              AWS:
                - !GetAtt CloudFormationDeployRole.Arn
                - !GetAtt CloudFormationExecutionRole.Arn

  # KMS S3 encryption key
  TrustStoreBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-s3
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
  TrustStoreBucketKMSKeyKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/TrustStoreBucketKMSKeyAlias
      TargetKeyId: !Ref TrustStoreBucketKMSKey

  TrustStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${TrustStoreBucketKMSKeyKMSKeyAlias}"
              SSEAlgorithm: "aws:kms"

  TrustStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrustStoreBucket
      PolicyDocument:
        Statement:
          - Effect: "Deny"
            Action: "s3:*"
            Principal: "*"
            Resource:
              - !Join ["", [!GetAtt TrustStoreBucket.Arn, "/*"]]
              - !GetAtt TrustStoreBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
          - Effect: "Allow"
            Action:
              - "s3:GetObject*"
              - "s3:PutObject*"
              - "s3:GetBucket*"
              - "s3:List*"
            Resource:
              - !Join ["", [!GetAtt TrustStoreBucket.Arn, "/*"]]
              - !GetAtt TrustStoreBucket.Arn
            Principal:
              AWS:
                - !GetAtt CloudFormationDeployRole.Arn
                - !GetAtt CloudFormationExecutionRole.Arn

  # KMS secrets encryption key
  SecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-s3
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
  SecretsKMSKeyKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/SecretsKMSKeyAlias
      TargetKeyId: !Ref SecretsKMSKey

  # secrets
  CAKeySecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CA private key
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  CACertSecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CA certificate
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  ClientKeySecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Client private key
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  ClientCertSecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Client cert
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  ClientSandboxKeySecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Client sandbox private key
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  ClientSandboxCertSecret:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Client sandbox cert
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  SpinePrivateKey:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for spine mutual TLS
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  SpinePublicCertificate:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public certificate for spine mutual TLS
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  SpineASID:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: ASID for spine
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  SpinePartyKey:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: PartyKey for spine
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

  SpineCAChain:
    DependsOn: SecretsKMSKeyKMSKeyAlias
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CA chain for spine
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe

Outputs:
  CloudFormationDeployRole:
    Description: ARN of the IAM Role(CloudFormationDeployRole)
    Value: !GetAtt CloudFormationDeployRole.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "CloudFormationDeployRole"]]
  CloudFormationExecutionRole:
    Description: ARN of the IAM Role(CloudFormationExecutionRole)
    Value: !GetAtt CloudFormationExecutionRole.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "CloudFormationExecutionRole"]]
  ArtifactsBucket:
    Description: ARN of the Artifacts bucket
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ArtifactsBucket"]]
  TrustStoreBucket:
    Description: ARN of the Truststore bucket
    Value: !GetAtt TrustStoreBucket.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "TrustStoreBucket"]]
  CAKeySecret:
    Description: ARN of the CA key secret
    Value: !GetAtt CAKeySecret.Id
  CACertSecret:
    Description: ARN of the CA cert secret
    Value: !GetAtt CACertSecret.Id
  ClientKeySecret:
    Description: ARN of the client key secret
    Value: !GetAtt ClientKeySecret.Id
  ClientCertSecret:
    Description: ARN of the client cert secret
    Value: !GetAtt ClientCertSecret.Id
  ClientSandboxKeySecret:
    Description: ARN of the client key secret for sandbox
    Value: !GetAtt ClientSandboxKeySecret.Id
  ClientSandboxCertSecret:
    Description: ARN of the client cert secret for sandbox
    Value: !GetAtt ClientSandboxCertSecret.Id
  SpinePrivateKey:
    Description: ARN of the private key for spine mutual TLS
    Value: !GetAtt SpinePrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SpinePrivateKey"]]
  SpinePublicCertificate:
    Description: ARN of the public certificate for spine mutual TLS
    Value: !GetAtt SpinePublicCertificate.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SpinePublicCertificate"]]
  SpineASID:
    Description: ASID for spine
    Value: !GetAtt SpineASID.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SpineASID"]]
  SpinePartyKey:
    Description: PartyKey for spine
    Value: !GetAtt SpinePartyKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SpinePartyKey"]]
  SecretsKMSKey:
    Description: SecretsKMSKey
    Value: !GetAtt SecretsKMSKey.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SecretsKMSKey"]]
  SpineCAChain:
    Description: SpineCAChain
    Value: !GetAtt SpineCAChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "SpineCAChain"]]
