AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PFP resources

Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  Env:
    Type: String
    Default: "dev"
    AllowedValues:
      - dev
      - dev-pr
      - qa
      - int
      - prod
      - ref

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  TargetSpineServer:
    Type: String
    Default: none

  TargetServiceSearchServer:
    Type: String
    Default: none

  LogLevel:
    Type: String
    Default: "INFO"

  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1096
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653

  EnableSplunk:
    Type: String
    Default: false
    AllowedValues: [true, false]

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  ToggleGetStatusUpdates:
    Type: String
    Default: false

  EnableAlerts:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  StateMachineLogLevel:
    Type: String

  ForwardCsocLogs:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  Apis:
    Type: AWS::Serverless::Application
    Properties:
      Location: apis/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        GetMyPrescriptionsStateMachineName: !GetAtt StateMachines.Outputs.GetMyPrescriptionsStateMachineName
        GetMyPrescriptionsStateMachineArn: !GetAtt StateMachines.Outputs.GetMyPrescriptionsStateMachineArn
        CapabilityStatementFunctionName: !GetAtt Functions.Outputs.CapabilityStatementFunctionName
        CapabilityStatementFunctionArn: !GetAtt Functions.Outputs.CapabilityStatementFunctionArn
        StatusFunctionName: !GetAtt Functions.Outputs.StatusFunctionName
        StatusFunctionArn: !GetAtt Functions.Outputs.StatusFunctionArn
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        ForwardCsocLogs: !Ref ForwardCsocLogs

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        Env: !Ref Env
        TargetSpineServer: !Ref TargetSpineServer
        TargetServiceSearchServer: !Ref TargetServiceSearchServer
        LogLevel: !Ref LogLevel
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId
        ToggleGetStatusUpdates: !Ref ToggleGetStatusUpdates

  StateMachines:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machines/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        GetMyPrescriptionsFunctionName: !GetAtt Functions.Outputs.GetMyPrescriptionsFunctionName
        GetMyPrescriptionsFunctionArn: !GetAtt Functions.Outputs.GetMyPrescriptionsFunctionArn
        EnrichPrescriptionsFunctionName: !GetAtt Functions.Outputs.EnrichPrescriptionsFunctionName
        EnrichPrescriptionsFunctionArn: !GetAtt Functions.Outputs.EnrichPrescriptionsFunctionArn
        LogRetentionInDays: !Ref LogRetentionInDays
        EnableSplunk: !Ref EnableSplunk
        StateMachineLogLevel: !Ref StateMachineLogLevel

  Alarms:
    Type: AWS::Serverless::Application
    Properties:
      Location: alarms/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        GetMyPrescriptionsFunctionName: !GetAtt Functions.Outputs.GetMyPrescriptionsFunctionName
        EnrichPrescriptionsFunctionName: !GetAtt Functions.Outputs.EnrichPrescriptionsFunctionName
        EnableAlerts: !Ref EnableAlerts
