AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: PFP state machines and related resources

Parameters:
  StackName:
    Type: String
    Description: The name of the main stack
    Default: none

  GetMyPrescriptionsFunctionName:
    Type: String
    Description: The function name of GetMyPrescriptions lambda
    Default: none

  GetMyPrescriptionsFunctionArn:
    Type: String
    Description: The function ARN of GetMyPrescriptions lambda
    Default: none

  LogRetentionInDays:
    Type: Number
    Description: How long to keep logs for

  EnableSplunk:
    Type: String
    Description: Whether to use splunk

  ToggleGetStatusUpdatesParameterName:
    Type: String
    Default: none

  ToggleGetStatusUpdatesParameterManagedPolicyArn:
    Type: String
    Default: none

Resources:
  GetMyPrescriptionsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-GetMyPrescriptions
      Type: EXPRESS
      Role: !GetAtt GetMyPrescriptionsStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: GetMyPrescriptionsStateMachine.asl.json
      DefinitionSubstitutions:
        GetMyPrescriptionsFunctionArn: !Sub ${GetMyPrescriptionsFunctionArn}:$LATEST
        GetStatusUpdatesFunctionArn: !Join
          - ":"
          - - !ImportValue psu-pr-98:functions:GSUL:GSULArn
            - $LATEST
        ToggleGetStatusUpdatesParameterName: !Ref ToggleGetStatusUpdatesParameterName
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt GetMyPrescriptionsStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL

  GetMyPrescriptionsStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-GetMyPrescriptions
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-GetMyPrescriptions
        AdditionalPolicies: !Join
          - ","
          - - Fn::ImportValue: !Sub ${StackName}:functions:${GetMyPrescriptionsFunctionName}:ExecuteLambdaPolicyArn
            - !ImportValue psu-pr-98:functions:psu-pr-98-GetStatusUpdates:ExecuteLambdaPolicyArn
            - !Ref ToggleGetStatusUpdatesParameterManagedPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

Outputs:
  GetMyPrescriptionsStateMachineArn:
    Description: GetMyPrescriptions state machine arn
    Value: !Ref GetMyPrescriptionsStateMachine

  GetMyPrescriptionsStateMachineName:
    Description: GetMyPrescriptions state machine name
    Value: !GetAtt GetMyPrescriptionsStateMachine.Name
