AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Resources for a state machine

Parameters:
  StackName:
    Type: String
    Default: none

  StateMachineName:
    Type: String
    Default: none

  StateMachineArn:
    Type: String
    Default: none

  AdditionalPolicies:
    Type: CommaDelimitedList
    Description: A list of additional policies to attach the state machines role (comma delimited).
    Default: none

  LogRetentionInDays:
    Type: Number

  CloudWatchKMSKeyId:
    Type: String
    Default: none

  EnableSplunk:
    Type: String

  SplunkSubscriptionFilterRole:
    Type: String
    Default: none

  SplunkDeliveryStreamArn:
    Type: String
    Default: none

Conditions:
  ShouldUseSplunk: !Equals
    - true
    - !Ref EnableSplunk

Resources:
  ExecuteStateMachineManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - states:StartSyncExecution
              - states:StartExecution
            Resource:
              - !Ref StateMachineArn

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      ManagedPolicyArns: !Split
        - ","
        - !Join
          - ","
          - - !Ref StateMachineManagedPolicy
            - !ImportValue account-resources:CloudwatchEncryptionKMSPolicyArn
            - !Join
              - ","
              - !Ref AdditionalPolicies

  StateMachineManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !GetAtt StateMachineLogGroup.Arn
              - !Sub ${StateMachineLogGroup.Arn}:log-stream:*
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:ListLogDeliveries
              - logs:CreateLogDelivery
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
            Resource: "*"

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/stepfunctions/${StateMachineName}
      RetentionInDays: !Ref LogRetentionInDays
      KmsKeyId: !Ref CloudWatchKMSKeyId

  StateMachineSplunkSubscriptionFilter:
    Condition: ShouldUseSplunk
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !Ref SplunkSubscriptionFilterRole
      LogGroupName: !Ref StateMachineLogGroup
      FilterPattern: ""
      DestinationArn: !Ref SplunkDeliveryStreamArn

Outputs:
  ExecuteStateMachinePolicyArn:
    Description: State machine execution policy arn
    Value: !Ref ExecuteStateMachineManagedPolicy
    Export:
      Name: !Sub ${StackName}:state-machines:${StateMachineName}:ExecuteStateMachinePolicy

  StateMachineRoleArn:
    Description: State machine role arn
    Value: !GetAtt StateMachineRole.Arn

  StateMachineLogGroupArn:
    Description: State machine log group arn
    Value: !GetAtt StateMachineLogGroup.Arn