AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: SSM parameters and related resources

Parameters:
  StackName:
    Type: String
    Description: The name of the main stack
    Default: none

  ToggleGetStatusUpdatesParameterName:
    Type: String
    Default: ToggleGetStatusUpdates

  ToggleGetStatusUpdatesParameterValue:
    Type: String

Resources:
  ToggleGetStatusUpdatesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-${ToggleGetStatusUpdatesParameterName}
      Type: String
      Value: !Ref ToggleGetStatusUpdatesParameterValue

  ToggleGetStatusUpdatesParameterManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-${ToggleGetStatusUpdatesParameterName}

Outputs:
  ToggleGetStatusUpdatesParameterName:
    Value: !Sub ${StackName}-${ToggleGetStatusUpdatesParameterName}

  ToggleGetStatusUpdatesParameterManagedPolicyArn:
    Value: !Ref ToggleGetStatusUpdatesParameterManagedPolicy
