AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: SSM parameters and related resources

Parameters:
  StackName:
    Type: String
    Description: The name of the main stack
    Default: none

  ToggleGetStatusUpdatesParameterValue:
    Type: String

Resources:
  ToggleGetStatusUpdatesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-ToggleGetStatusUpdates
      Type: String
      Value: !Ref ToggleGetStatusUpdatesParameterValue

  ToggleGetStatusUpdatesParameterManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ToggleGetStatusUpdatesParameter}

Outputs:
  ToggleGetStatusUpdatesParameterName:
    Value: !Ref ToggleGetStatusUpdatesParameter

  ToggleGetStatusUpdatesParameterManagedPolicyArn:
    Value: !Ref ToggleGetStatusUpdatesParameterManagedPolicy
    Export:
      Name: !Sub ${StackName}:parameters:${StackName}-ToggleGetStatusUpdates:ManagedPolicyArn
