AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Resources for an API

Parameters:
  AdditionalPolicies:
    Type: CommaDelimitedList
    Description: A list of additional policies to attach to the API gateway role (comma delimited).
    Default: none

  ApiName:
    Type: String
    Default: none

  LogRetentionInDays:
    Type: Number

  EnableSplunk:
    Type: String
  ForwardCsocLogs:
    Type: String
    Default: false

Conditions:
  ShouldUseSplunk: !Equals
    - true
    - !Ref EnableSplunk
  ShouldForwardCsocLogs: !Equals
    - true
    - !Ref ForwardCsocLogs
  HasAdditionalPolicies: !Not
    - !Equals
      - !Join [",", !Ref AdditionalPolicies]
      - "none"

Resources:
  ApiGwRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      # Only add ManagedPolicyArns if AdditionalPolicies is not 'none'
      ManagedPolicyArns: !If
        - HasAdditionalPolicies
        - !Split
          - ","
          - !Join
            - ","
            - - !Join
                - ","
                - !Ref AdditionalPolicies
        - !Ref "AWS::NoValue"

  ApiGwAccessLogs:
    Type: AWS::Logs::LogGroup
    Metadata:
      guard:
        SuppressedRules:
          - CW_LOGGROUP_RETENTION_PERIOD_CHECK
    Properties:
      LogGroupName: !Sub /aws/apigateway/${ApiName}
      RetentionInDays: !Ref LogRetentionInDays
      KmsKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn

  ApiGwAccessLogsSplunkSubscriptionFilter:
    Condition: ShouldUseSplunk
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
      LogGroupName: !Ref ApiGwAccessLogs
      FilterPattern: ""
      DestinationArn: !ImportValue lambda-resources:SplunkDeliveryStream

  ApiGwAccessLogsCsocSubscriptionFilter:
    Condition: ShouldForwardCsocLogs
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      RoleArn: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
      LogGroupName: !Ref ApiGwAccessLogs
      FilterPattern: ""
      DestinationArn: "arn:aws:logs:eu-west-2:693466633220:destination:api_gateway_log_destination"

Outputs:
  ApiGwRoleArn:
    Description: The API GW role ARN
    Value: !GetAtt ApiGwRole.Arn

  ApiGwAccessLogsArn:
    Description: The API GW access logs ARN
    Value: !GetAtt ApiGwAccessLogs.Arn
