name: "Create confluence release notes"
description: "Do release note actions in confluence and jira"
inputs:
  RELEASE_TAG:
    required: false
    description: "The tag we are marking as released in jira"
  DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE:
    required: true
    description: "The dev cloud formation deploy role"
  DRY_RUN:
    required: false
    description: "whether to use a dry run and do not connect to anything"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: connect to dev account
      if: ${{ inputs.DRY_RUN }} != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}
        role-session-name: account-resources-release-notes-run-lambda
    - name: call markJiraReleased lambda
      shell: bash
      working-directory: .github/scripts
      env:
        DRY_RUN: ${{ inputs.DRY_RUN }}
        RELEASE_TAG: ${{ inputs.RELEASE_TAG }}
      run: ./call_mark_jira_released.sh
