name: "Scan SBOM for vulnerabilities"

on:
  workflow_call:

jobs:

  scan-node-vulnerabilities:
    runs-on: ubuntu-latest
    steps:      
      - name: Download SBOM artifacts
        uses: actions/download-artifact@v4
        with:
          name: SBOMs

      - name: Extract SBOM artifacts
        run: |
          unzip SBOMs.zip -d sboms

      - uses: anchore/scan-action@v3
        with:
          sbom: sboms/sbom-node.json
          fail-build: true
          severity-cutoff: critical
          
