name: Auto-approve dependency updates

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions: {}
jobs:
  auto-approve-dependabot:
    runs-on: ubuntu-22.04
    environment: create_pull_request
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto approve and enable auto-merge
        uses: NHSDigital/eps-dependabot-approve@55da79f2effe6726785ad3675e92c6db87f77156
        with:
          AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
          AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}