name: 'Create confluence release notes'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create_confluence_release_notes:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@4f8f7939dd917fc656bb7c3575969a5988c28364
        with:
          asdf_branch: v0.11.3
  
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared 
  
      - name: make install
        run: |
          export PATH="/home/runner/.asdf/installs/poetry/1.3.1/bin:$PATH"
          make install

      - name: Configure dev AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - shell: bash
        name: get dev tag
        run: |
          export dev_tag=$(aws cloudformation describe-stacks --stack-name dev-ci --query 'Stacks[0].Tags[?Key==`version`].Value' --output text)

      - name: Configure int AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - shell: bash
        name: get int tag
        run: |
          export int_tag=$(aws cloudformation describe-stacks --stack-name int-ci --query 'Stacks[0].Tags[?Key==`version`].Value' --output text)

      - name: Configure prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.PROD_CLOUD_FORMATION_DEPLOY_ROLE }}
          role-session-name: github-actions

      - shell: bash
        name: get prod tag
        run: |
          export prod_tag=$(aws cloudformation describe-stacks --stack-name prod-ci --query 'Stacks[0].Tags[?Key==`version`].Value' --output text)

      - shell: bash
        name: create int release notes
        run: |
          make publish-release-notes-int

      - shell: bash
        name: create prod release notes
        run: |
          make publish-release-notes-prod
          
