name: "Delete old pull request deployments"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

permissions: {}
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@889349f9d93e4846a642f7973b7c26b180bec5aa
    with:
      verify_published_from_main_image: false
    permissions:
      attestations: read
      contents: read
      packages: read
  delete-old-cloudformation-stacks:
    needs: [get_config_values]
    runs-on: ubuntu-22.04
    container:
      image: ${{ needs.get_config_values.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions: &common_permissions
      id-token: write
      contents: read
      packages: read

    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - &checkout
        name: Checkout local github scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install_dependencies
        name: install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}

      - name: delete stacks
        shell: bash
        run: npm run delete-old-pr-stacks --workspace packages/cdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-old-proxygen-deployments:
    needs: [get_config_values]
    runs-on: ubuntu-22.04
    container:
      image: ${{ needs.get_config_values.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions: *common_permissions

    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - *checkout
      - *install_dependencies

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.PROXYGEN_PTL_ROLE }}

      - name: delete proxygen deployments
        shell: bash
        run: npm run delete-old-pr-deployments --workspace packages/specification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
