name: Generate SBOM

on:
  push:
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies using Makefile
        run: |
          make install

      - name: Install Python SBOM generator
        run: pip install cyclonedx-bom

      - name: Generate Python SBOM
        run: |
          cyclonedx-py poetry > sbom-python.json

      - name: Install Node.js SBOM generator
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate Node.js SBOM
        run: |
          cyclonedx-npm --output-format json --output-file sbom-node.json

      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SBOMs
          path: |
            sbom-python.json
            sbom-node.json
