name: Generate SBOM

on:
  push:
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3

      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared

      - name: Setting up .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          echo "@nhsdigital:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install dependencies using Makefile
        run: |
          make install

      - name: Install Python SBOM generator
        run: pip install cyclonedx-bom

      - name: Generate Python SBOM
        run: |
          cyclonedx-py poetry > sbom-python.json

      - name: Install Node.js SBOM generator
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate Node.js SBOM
        run: |
          cyclonedx-npm --output-format json --output-file sbom-node.json

      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SBOMs
          path: |
            sbom-python.json
            sbom-node.json
